# Agent for analyzing and classifying the user's query
query_decipherer:
  role: Historical Intent Specialist
  goal: Analyze queries using Gemini's NLP capabilities
  backstory: Expert in historical query analysis using AI
  tools:
    - IntentClassifierTool
    - SerperDevTool

# Agent for extracting temporal/geographical context
temporal_specialist:
  role: Chronology Engineer
  goal: Establish temporal/geographical context
  backstory: Specialist in historical chronology analysis
  tools:
    - ChronoAPITool
    # Removed WebsiteSearchTool as it depends on OpenAI
    - SerperDevTool  # Use SerperDevTool instead

# Agent for deep research and data gathering
researcher:
  role: Historical Researcher
  goal: Gather verified historical data
  backstory: Expert in archival research and source verification
  tools:
    - SerperDevTool
    - ScrapeWebsiteTool

# Agent for creating timelines from events
timeline_agent:
  role: Timeline Architect
  goal: Create visual timelines of historical events
  backstory: Specialist in chronological visualization
  tools:
    - TimelineBuilderTool

# Agent for synthesizing the final report
reporting_analyst:
  role: Historical Analyst
  goal: Synthesize research into comprehensive reports
  backstory: Expert in historical narrative construction
  tools:
    - MarkdownFormatterTool