# Task: Analyze the user's historical query
query_analysis:
  description: "Analyze the historical query: '{topic}'"
  expected_output: JSON with query type and key entities

# Task: Establish historical timeframe and locations
temporal_context:
  description: "Establish historical timeframe and locations for: '{topic}'"
  expected_output: JSON timeline boundaries and locations

# Task: Conduct deep historical research
research:
  description: "Conduct deep historical research on: '{topic}'"
  expected_output: Verified historical data with sources

# Task: Generate visual timeline of events
timeline_creation:
  description: "Generate visual timeline of events for: '{topic}'"
  expected_output: Markdown timeline with dates and events

# Task: Create final report with timeline
reporting:
  description: "Create final historical report about: '{topic}'"
  expected_output: Comprehensive markdown report